using Grimoire.Connector.OracleEbs.Registry;

namespace Grimoire.Connector.OracleEbs.Modules;

internal sealed class EamModule : IEbsModule
{
    public string ModuleName => "EAM";

    public void Register(EbsRegistry registry)
    {
        // Equipment Master
        registry.Table("EAM_EQUIPMENT_SERIAL_NUM", "EAM_EQUIPMENT_SERIAL_NUM", "EAM", "EAM")
            .Column("SERIAL_NUM", since: EbsVersion.R12)
            .Column("EQUIPMENT_NAME", since: EbsVersion.R12)
            .Column("DESCRIPTION", since: EbsVersion.R12)
            .Column("EQUIPMENT_CLASS_CODE", since: EbsVersion.R12)
            .Column("ASSET_NUMBER", since: EbsVersion.R12)
            .Column("INSTALLATION_DATE", since: EbsVersion.R12)
            .Column("CURRENT_LOCATION_ID", since: EbsVersion.R12)
            .Column("EQUIPMENT_STATUS_CODE", since: EbsVersion.R12)
            .Column("MANUFACTURER_CODE", since: EbsVersion.R12)
            .Column("MODEL_CODE", since: EbsVersion.R12)
            .Column("SERIAL_NUMBER_EBS", since: EbsVersion.R12)
            .Column("ORG_ID", since: EbsVersion.R12)
            .Column("CREATED_BY", since: EbsVersion.R12)
            .Column("CREATION_DATE", since: EbsVersion.R12)
            .Column("LAST_UPDATED_BY", since: EbsVersion.R12)
            .Column("LAST_UPDATE_DATE", since: EbsVersion.R12)
            .JoinTo("EAM_ACTIVITY_HISTORY", "SERIAL_NUM", "SERIAL_NUM", since: EbsVersion.R12)
            .JoinTo("EAM_WORK_ORDERS", "SERIAL_NUM", "SERIAL_NUM", since: EbsVersion.R12)
            .JoinTo("EAM_SCHEDULED_WORK_ORDERS", "SERIAL_NUM", "SERIAL_NUM", since: EbsVersion.R12)
            .JoinTo("EAM_OR_NETWORKS", "SERIAL_NUM", "SERIAL_NUM", since: EbsVersion.R12);

        // Activity History (Transaction Ledger - Full Depth)
        registry.Table("EAM_ACTIVITY_HISTORY", "EAM_ACTIVITY_HISTORY", "EAM", "EAM")
            .Column("ACTIVITY_ID", since: EbsVersion.R12)
            .Column("SERIAL_NUM", since: EbsVersion.R12)
            .Column("ACTIVITY_TYPE_CODE", since: EbsVersion.R12)
            .Column("TRANSACTION_DATE", since: EbsVersion.R12)
            .Column("SCHEDULED_START_DATE", since: EbsVersion.R12)
            .Column("WORK_ORDER_ID", since: EbsVersion.R12)
            .Column("FAILURE_CODE", since: EbsVersion.R12)
            .Column("CORRECTIVE_ACTION_CODE", since: EbsVersion.R12)
            .Column("ACTION_DESCRIPTION", since: EbsVersion.R12)
            .Column("ACTIVITY_COST", since: EbsVersion.R12)
            .Column("LABOR_HOURS", since: EbsVersion.R12)
            .Column("MATERIAL_COST", since: EbsVersion.R12)
            .Column("ACTIVITY_STATUS_CODE", since: EbsVersion.R12)
            .Column("ORG_ID", since: EbsVersion.R12)
            .Column("CREATED_BY", since: EbsVersion.R12)
            .Column("CREATION_DATE", since: EbsVersion.R12)
            .Column("LAST_UPDATED_BY", since: EbsVersion.R12)
            .Column("LAST_UPDATE_DATE", since: EbsVersion.R12)
            .JoinTo("EAM_EQUIPMENT_SERIAL_NUM", "SERIAL_NUM", "SERIAL_NUM", since: EbsVersion.R12)
            .JoinTo("EAM_WORK_ORDERS", "WORK_ORDER_ID", "WORK_ORDER_ID", since: EbsVersion.R12);

        // Work Orders (Transaction Header)
        registry.Table("EAM_WORK_ORDERS", "EAM_WORK_ORDERS", "EAM", "EAM")
            .Column("WORK_ORDER_ID", since: EbsVersion.R12)
            .Column("WORK_ORDER_NUMBER", since: EbsVersion.R12)
            .Column("SERIAL_NUM", since: EbsVersion.R12)
            .Column("ORGANIZATION_ID", since: EbsVersion.R12)
            .Column("WORK_ORDER_TYPE_CODE", since: EbsVersion.R12)
            .Column("PRIORITY_CODE", since: EbsVersion.R12)
            .Column("STATUS_CODE", since: EbsVersion.R12)
            .Column("SCHEDULED_START_DATE", since: EbsVersion.R12)
            .Column("ACTUAL_START_DATE", since: EbsVersion.R12)
            .Column("SCHEDULED_END_DATE", since: EbsVersion.R12)
            .Column("ACTUAL_END_DATE", since: EbsVersion.R12)
            .Column("ASSIGNED_TO_PERSON_ID", since: EbsVersion.R12)
            .Column("TOTAL_COST", since: EbsVersion.R12)
            .Column("LABOR_COST", since: EbsVersion.R12)
            .Column("MATERIAL_COST", since: EbsVersion.R12)
            .Column("ORG_ID", since: EbsVersion.R12)
            .Column("CREATED_BY", since: EbsVersion.R12)
            .Column("CREATION_DATE", since: EbsVersion.R12)
            .Column("LAST_UPDATED_BY", since: EbsVersion.R12)
            .Column("LAST_UPDATE_DATE", since: EbsVersion.R12)
            .JoinTo("EAM_EQUIPMENT_SERIAL_NUM", "SERIAL_NUM", "SERIAL_NUM", since: EbsVersion.R12)
            .JoinTo("EAM_WO_ACTIVITIES", "WORK_ORDER_ID", "WORK_ORDER_ID", since: EbsVersion.R12);

        // Work Order Activities (Transaction Detail)
        registry.Table("EAM_WO_ACTIVITIES", "EAM_WO_ACTIVITIES", "EAM", "EAM")
            .Column("WO_ACTIVITY_ID", since: EbsVersion.R12)
            .Column("WORK_ORDER_ID", since: EbsVersion.R12)
            .Column("ACTIVITY_SEQUENCE_NUMBER", since: EbsVersion.R12)
            .Column("ACTIVITY_CODE", since: EbsVersion.R12)
            .Column("ACTIVITY_DESCRIPTION", since: EbsVersion.R12)
            .Column("SCHEDULED_DURATION", since: EbsVersion.R12)
            .Column("ACTUAL_DURATION", since: EbsVersion.R12)
            .Column("ASSIGNED_PERSON_ID", since: EbsVersion.R12)
            .Column("ACTIVITY_STATUS_CODE", since: EbsVersion.R12)
            .Column("CREATED_BY", since: EbsVersion.R12)
            .Column("CREATION_DATE", since: EbsVersion.R12)
            .Column("LAST_UPDATED_BY", since: EbsVersion.R12)
            .Column("LAST_UPDATE_DATE", since: EbsVersion.R12)
            .JoinTo("EAM_WORK_ORDERS", "WORK_ORDER_ID", "WORK_ORDER_ID", since: EbsVersion.R12);

        // Scheduled Work Orders (Schedule/Event)
        registry.Table("EAM_SCHEDULED_WORK_ORDERS", "EAM_SCHEDULED_WORK_ORDERS", "EAM", "EAM")
            .Column("SCHEDULED_WO_ID", since: EbsVersion.R12)
            .Column("SERIAL_NUM", since: EbsVersion.R12)
            .Column("SCHEDULE_NAME", since: EbsVersion.R12)
            .Column("SCHEDULE_TYPE_CODE", since: EbsVersion.R12)
            .Column("FREQUENCY_CODE", since: EbsVersion.R12)
            .Column("LAST_RUN_DATE", since: EbsVersion.R12)
            .Column("NEXT_RUN_DATE", since: EbsVersion.R12)
            .Column("NEXT_WORK_ORDER_ID", since: EbsVersion.R12)
            .Column("ENABLED_FLAG", since: EbsVersion.R12)
            .Column("ACTIVE_FLAG", since: EbsVersion.R12)
            .Column("ORG_ID", since: EbsVersion.R12)
            .Column("CREATED_BY", since: EbsVersion.R12)
            .Column("CREATION_DATE", since: EbsVersion.R12)
            .Column("LAST_UPDATED_BY", since: EbsVersion.R12)
            .Column("LAST_UPDATE_DATE", since: EbsVersion.R12)
            .JoinTo("EAM_EQUIPMENT_SERIAL_NUM", "SERIAL_NUM", "SERIAL_NUM", since: EbsVersion.R12);

        // Equipment Hierarchy (Reference Structure)
        registry.Table("EAM_OR_NETWORKS", "EAM_OR_NETWORKS", "EAM", "EAM")
            .Column("NETWORK_ID", since: EbsVersion.R12)
            .Column("SERIAL_NUM", since: EbsVersion.R12)
            .Column("PARENT_SERIAL_NUM", since: EbsVersion.R12)
            .Column("RELATIONSHIP_TYPE_CODE", since: EbsVersion.R12)
            .Column("NETWORK_NAME", since: EbsVersion.R12)
            .Column("CREATED_BY", since: EbsVersion.R12)
            .Column("CREATION_DATE", since: EbsVersion.R12)
            .Column("LAST_UPDATED_BY", since: EbsVersion.R12)
            .Column("LAST_UPDATE_DATE", since: EbsVersion.R12)
            .JoinTo("EAM_EQUIPMENT_SERIAL_NUM", "PARENT_SERIAL_NUM", "SERIAL_NUM", since: EbsVersion.R12);
    }
}
